### ISSUE TITLE
Failed to decode json returned from code runner

### ISSUE THREAD

**Issue by mguzhuman** [glotcode/docker-run#1]
Hello. I installed docker-run according to the [instructions](https://github.com/glotcode/docker-run/blob/main/docs/install/ubuntu-20.10.md).  When asked to execute the code, I get the following response: `Failed to decode json returned from code runner: EOF while parsing a value at line 1 column 0`. 

`curl http://localhost:8088`
> {
  "name": "docker-run",
  "version": "1.0.0",
  "description": "Api for running code in transient docker containers"
}

`curl --header 'X-Access-Token: token' http://localhost:8088/version`
>{
  "docker": {
    "version": "19.03.8",
    "apiVersion": "1.40",
    "gitCommit": "afacb8b7f0",
    "goVersion": "go1.13.8",
    "os": "linux",
    "arch": "amd64",
    "kernelVersion": "5.4.0-48-generic",
    "buildTime": "2020-12-04T23:02:49.000000000+00:00",
    "platform": {
      "name": ""
    },
    "components": [
      {
        "name": "Engine",
        "version": "19.03.8"
      },
      {
        "name": "containerd",
        "version": "1.3.3-0ubuntu2"
      },
      {
        "name": "runc",
        "version": "spec: 1.0.1-dev"
      },
      {
        "name": "docker-init",
        "version": "0.18.0"
      }
    ]
  }

`curl --request POST --header 'X-Access-Token: token' --header 'Content-type: application/json' --data '{"image": "glot/python:latest", "payload": {"language": "python", "files": [{"name": "main.py", "content": "print(42)"}]}}' http://localhost:8088/run`
>{
  "error": "coderunner.stdout.decode",
  "message": "Failed to decode json returned from code runner: EOF while parsing a value at line 1 column 0"
}

**Comment by prasmussen** [comment]
Not sure about this one. It would be interesting to see the logs of the container when this happens.

I just released a new version [1.1.0](https://github.com/glotcode/docker-run/releases), which let's you set the following config option to keep containers around:
```bash
DEBUG_KEEP_CONTAINER="true"
```

You can then find the container with `docker ps -a` and see its logs with `docker logs --details <containerId>`

**Comment by mguzhuman** [comment]
@prasmussen  cmd: `sudo docker logs --details 7c72631293f1`
answer : ` standard_init_linux.go:211: exec user process caused "resource temporarily unavailable"`

This time I tried javascript and the error is the same.

**Comment by prasmussen** [comment]
Thanks, my initial thought is that this is some problem with you docker installation.

Are you able to run the hello-world image?
```docker run hello-world```

**Comment by mguzhuman** [comment]
@prasmussen Here it is: 

```
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by prasmussen** [comment]
I'm able to reproduce the problem if I set the NPROC options to 0, you could try setting them to higher number, i.e:
```bash
DOCKER_CONTAINER_ULIMIT_NPROC_SOFT="1000"
DOCKER_CONTAINER_ULIMIT_NPROC_HARD="1000"
```

**Comment by mguzhuman** [comment]
@prasmussen Managed to solve the problem on linux. I created a docker container for docker-run and run with the command `-v /var/run/docker.sock:/var/run/docker.sock`
